---
- hosts: rhel_kvm
  name: play to turn on IDM and Undercloud
  gather_facts: false
  remote_user: root
  tasks:
  - name: start undercloud and idm
    shell: "virsh start {{ item.name }}"
    ignore_errors: true
    with_items: "{{ vmenator.vms }}"

- hosts: rhel_idm
  name: play to check on IDM
  gather_facts: false
  remote_user: root
  tasks:
  - name: waiting for IDM to be online
    wait_for:
      host: "{{ inventory_hostname }}"
      state: started
      connect_timeout: 5
      timeout: 300
      port: 22
    delegate_to: 127.0.0.1
    become: false

- hosts: rhosp_director
  name: playbook to startup all systems and services
  gather_facts: false
  remote_user: root
  become_user: stack
  tasks:
  - name: waiting for Undercloud to be online
    wait_for:
      host: "{{ inventory_hostname }}"
      state: started
      connect_timeout: 5
      timeout: 300
      port: 22
    delegate_to: 127.0.0.1
    become: false

  - name: Pause playbook execution for 30 seconds
    pause:
      seconds: 30

  - name: get ironic node names for overcloud hosts
    become: yes
    become_user: stack
    shell: "source /home/stack/stackrc && openstack baremetal node list -c Name --format value"
    register: overcloud_host_node_names

  - name: poweron overcloud hosts
    become: yes
    become_user: stack
    shell: "source /home/stack/stackrc && ironic node-set-power-state {{ item }} on"
    with_items:
      - "{{ overcloud_host_node_names.stdout_lines }}"

  - name: get provisioning IPs for overcloud hosts
    become: yes
    become_user: stack
    shell: "source /home/stack/stackrc && openstack server list -c Networks --format value | cut -d = -f 2"
    register: overcloud_host_prov_ips

  - name: waiting for overcloud hosts to poweron
    wait_for:
      host: "{{ item }}"
      state: started
      connect_timeout: 5
      timeout: 300
      port: 22
    delegate_to: 127.0.0.1
    become: false
    ignore_errors: true
    with_items:
      - "{{ overcloud_host_prov_ips.stdout_lines }}"

  - name: waiting for horizon to come online
    wait_for:
      host: "{{ networks.external.dhcpStart }}"
      state: started
      connect_timeout: 5
      timeout: 300
      port: 80
    delegate_to: 127.0.0.1
    become: false

  - name: Pause playbook execution for 30 seconds
    pause:
      seconds: 30

  #due to weird issue on pod1 where patternfly doesn't load
  #- name: get provisioning IPs for overcloud controllers
  #  become: yes
  #  become_user: stack
  #  shell: "source /home/stack/stackrc && openstack server list -f value | grep controller | cut -d = -f 2 | cut -d ' ' -f 1"
  #  register: overcloud_controller_prov_ips

  #- name: restart httpd on controllers
  #  become: yes
  #  become_user: stack
  #  shell: "ssh heat-admin@{{ item }} sudo systemctl restart httpd"
  #  with_items:
  #    - "{{ overcloud_controller_prov_ips.stdout_lines }}"

  #- name: Pause playbook execution for 30 seconds
  #  pause:
  #    seconds: 30


- hosts: rhel_kvm
  name: play to start OpenStack instances
  gather_facts: false
  remote_user: root
  tasks:
  - name: authenticate to the cloud and retrieve the service catalog
    os_auth:
      auth: "{{ os_auth | default(omit) }}"

#- hosts: rhosp_director
#  name: play to start OpenStack instances
#  gather_facts: false
#  remote_user: root
#  tasks:
#  - name: get list of openstack projects
#    become: yes
#    become_user: stack
#    shell: "source /home/stack/operatorrc && openstack project list -c Name --format value"
#    delegate_to: "{{ rhosp_director_ip }}"
#    register: openstack_projects

#  - name: set openstack_projects fact
#    set_fact:
#      openstack_projects: "{{ openstack_projects }}"

#- hosts: localhost
#  name: play to start OpenStack instances
#  gather_facts: false
#  remote_user: root
#  tasks:
  - name: get list of openstack projects
    os_project_facts:
      auth: "{{ os_auth | default(omit) }}"

  - name: get list of instances per project
    os_server_facts:
      auth: "{{ os_auth | default(omit) }}"
    with_items:
      - "{{ openstack_projects }}"
    ignore_errors: true

  - debug:
      msg: "{{ openstack_projects }}"
  - debug:
      msg: "{{ openstack_servers }}"
  
  - name: start all instances in each project
    os_server_action:
      action: start
      auth: "{{ os_auth | default(omit) }}"
      server: "{{ item.name }}"
      timeout: 200
      wait: yes
    with_items:
      - "{{ openstack_servers }}"
    ignore_errors: true
